### PR TITLE
feat: support running on wasm32 target and browser

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Review by doitian — APPROVED** [review]

**Comment by doitian** [comment]
Rust no longer provides .exe installer in latest versions.

**Comment by doitian** [comment]
Save the patch and apply it

```
git am 0001-chore-ci-install-rust-using-rustup-in-appveyor.patch
```

```diff
From d670eb9212f01a9b02e4fffcadc064fc37f55e7f Mon Sep 17 00:00:00 2001
From: ian <ian@nervos.org>
Date: Tue, 15 Dec 2020 19:09:53 +0800
Subject: [PATCH] chore(ci): install rust using rustup in appveyor

---
 appveyor.yml | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/appveyor.yml b/appveyor.yml
index e5913a1..c0dc6be 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -11,10 +11,10 @@ environment:
       RUST_VERSION: 1.46.0

 install:
-  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:RUST_INSTALL_TRIPLE}.exe"
-  - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /DIR="%RUST_INSTALL_DIR%"
+  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:RUST_INSTALL_TRIPLE}/rustup-init.exe"
+  - cmd: rustup-init.exe -yv --default-toolchain %RUST_VERSION% --default-host %RUST_INSTALL_TRIPLE%
   - cmd: CALL "%VCVARS%"
-  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
+  - cmd: SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
   - rustc --version
   - cargo --version

--
2.25.1
```

**Comment by quake** [comment]
@doitian applied patch, please review again, thanks

**Comment by doitian** [comment]
v0.2.1 published to crates.io

**Pull request merged**
